project_id = "aiflfkkjitvsyszwdfga"

[functions.admin-users]
verify_jwt = false

[functions.platform-signup]
verify_jwt = false

[functions.send-invite-email]
verify_jwt = false

[functions.send-push]
verify_jwt = false
