project_id = "aiflfkkjitvsyszwdfga"

[functions.admin-users]
verify_jwt = false

[functions.platform-signup]
verify_jwt = false

[functions.send-invite-email]
verify_jwt = false

[functions.send-reset-email]
verify_jwt = false

[functions.send-push]
verify_jwt = false

[functions.meta-oauth-callback]
verify_jwt = false

[functions.meta-app-id]
verify_jwt = false

[functions.cleanup-orphan-media]
verify_jwt = false

[functions.migrate-to-r2]
verify_jwt = false

[functions.r2-presign]
verify_jwt = false

[functions.meta-sync-leads]
verify_jwt = false

[functions.meta-sync-entities]
verify_jwt = false

[functions.onesignal-app-id]
verify_jwt = false

[functions.cloudflare-purge-cache]
verify_jwt = false

[functions.admin-subscriptions]
verify_jwt = false

[functions.rd-station-webhook]
verify_jwt = false

[functions.meta-save-account]
verify_jwt = false

[functions.ticket-chat]
verify_jwt = false

[functions.rd-station-sync-leads]
verify_jwt = false

[functions.rd-station-oauth-callback]
verify_jwt = false

[functions.rd-station-app-id]
verify_jwt = false

[functions.rd-station-send-event]
verify_jwt = false

[functions.toggle-maintenance-mode]
verify_jwt = false

[functions.export-database]
verify_jwt = false
