-- Public edge functions security controls:
-- - Centralized rate limiting primitives
-- - Request logging for abuse detection and monitoring
-- - Anomaly detection function for alerting integrations

CREATE TABLE IF NOT EXISTS public.function_rate_limits (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  function_name TEXT NOT NULL,
  principal TEXT NOT NULL,
  window_start TIMESTAMPTZ NOT NULL,
  requests_count INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT function_rate_limits_unique_window UNIQUE (function_name, principal, window_start)
);

CREATE INDEX IF NOT EXISTS idx_function_rate_limits_lookup
  ON public.function_rate_limits (function_name, principal, window_start DESC);

CREATE TABLE IF NOT EXISTS public.function_request_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  function_name TEXT NOT NULL,
  principal TEXT,
  status_code INTEGER NOT NULL,
  outcome TEXT NOT NULL,
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_function_request_logs_created_at
  ON public.function_request_logs (created_at DESC);

CREATE INDEX IF NOT EXISTS idx_function_request_logs_function_time
  ON public.function_request_logs (function_name, created_at DESC);

ALTER TABLE public.function_rate_limits ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.function_request_logs ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "No direct access to function_rate_limits" ON public.function_rate_limits;
CREATE POLICY "No direct access to function_rate_limits"
ON public.function_rate_limits
FOR ALL
TO authenticated, anon
USING (false)
WITH CHECK (false);

DROP POLICY IF EXISTS "No direct access to function_request_logs" ON public.function_request_logs;
CREATE POLICY "No direct access to function_request_logs"
ON public.function_request_logs
FOR ALL
TO authenticated, anon
USING (false)
WITH CHECK (false);

CREATE OR REPLACE FUNCTION public.consume_public_function_rate_limit(
  p_function_name TEXT,
  p_principal TEXT,
  p_limit INTEGER,
  p_window_seconds INTEGER
)
RETURNS TABLE(allowed BOOLEAN, requests_count INTEGER, retry_after_seconds INTEGER)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_now TIMESTAMPTZ := now();
  v_window_start TIMESTAMPTZ;
  v_bucket_count INTEGER;
BEGIN
  IF p_limit <= 0 THEN
    RAISE EXCEPTION 'p_limit must be greater than zero';
  END IF;

  IF p_window_seconds <= 0 THEN
    RAISE EXCEPTION 'p_window_seconds must be greater than zero';
  END IF;

  v_window_start := to_timestamp(floor(extract(epoch from v_now) / p_window_seconds) * p_window_seconds);

  INSERT INTO public.function_rate_limits(function_name, principal, window_start, requests_count)
  VALUES (p_function_name, p_principal, v_window_start, 1)
  ON CONFLICT (function_name, principal, window_start)
  DO UPDATE SET
    requests_count = public.function_rate_limits.requests_count + 1,
    updated_at = now()
  RETURNING function_rate_limits.requests_count INTO v_bucket_count;

  RETURN QUERY
  SELECT
    (v_bucket_count <= p_limit) AS allowed,
    v_bucket_count,
    GREATEST(0, p_window_seconds - (extract(epoch from (v_now - v_window_start)))::INTEGER) AS retry_after_seconds;
END;
$$;

CREATE OR REPLACE FUNCTION public.log_public_function_request(
  p_function_name TEXT,
  p_status_code INTEGER,
  p_outcome TEXT,
  p_principal TEXT DEFAULT NULL,
  p_metadata JSONB DEFAULT '{}'::jsonb
)
RETURNS BIGINT
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_id BIGINT;
BEGIN
  INSERT INTO public.function_request_logs(function_name, principal, status_code, outcome, metadata)
  VALUES (
    p_function_name,
    p_principal,
    p_status_code,
    p_outcome,
    COALESCE(p_metadata, '{}'::jsonb)
  )
  RETURNING id INTO v_id;

  RETURN v_id;
END;
$$;

CREATE OR REPLACE FUNCTION public.get_public_function_anomaly_candidates(
  p_since INTERVAL DEFAULT '15 minutes'
)
RETURNS TABLE(
  function_name TEXT,
  total_requests BIGINT,
  total_errors BIGINT,
  error_rate NUMERIC,
  unique_principals BIGINT
)
LANGUAGE sql
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT
    l.function_name,
    COUNT(*)::BIGINT AS total_requests,
    COUNT(*) FILTER (WHERE l.status_code >= 400)::BIGINT AS total_errors,
    ROUND(
      (COUNT(*) FILTER (WHERE l.status_code >= 400)::NUMERIC / NULLIF(COUNT(*), 0)::NUMERIC) * 100,
      2
    ) AS error_rate,
    COUNT(DISTINCT COALESCE(l.principal, 'anonymous'))::BIGINT AS unique_principals
  FROM public.function_request_logs l
  WHERE l.created_at >= now() - p_since
  GROUP BY l.function_name
  HAVING
    COUNT(*) >= 100
    OR COUNT(*) FILTER (WHERE l.status_code = 429) >= 20
    OR (COUNT(*) FILTER (WHERE l.status_code >= 400)::NUMERIC / NULLIF(COUNT(*), 0)::NUMERIC) >= 0.20
  ORDER BY total_requests DESC;
$$;
