// This file is automatically generated. Do not edit it directly.
import { createClient, SupportedStorage } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL ?? 'http://127.0.0.1:54321';
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ?? 'public-anon-key';

export type AuthStorageStrategy = 'local' | 'session';

export const AUTH_STORAGE_STRATEGY_KEY = 'habitae.auth.storage-strategy';
const DEFAULT_AUTH_STORAGE_STRATEGY: AuthStorageStrategy = 'local';

const isBrowser = () => typeof window !== 'undefined';

const getStorageByStrategy = (strategy: AuthStorageStrategy): Storage | null => {
  if (!isBrowser()) return null;
  return strategy === 'session' ? window.sessionStorage : window.localStorage;
};

const getAuthTokenKeys = (storage: Storage): string[] => {
  const keys: string[] = [];
  for (let i = 0; i < storage.length; i += 1) {
    const key = storage.key(i);
    if (!key) continue;
    if (key.includes('-auth-token') || key === 'supabase.auth.token') {
      keys.push(key);
    }
  }
  return keys;
};

const migrateAuthTokens = (from: Storage, to: Storage) => {
  const keys = getAuthTokenKeys(from);
  keys.forEach((key) => {
    const value = from.getItem(key);
    if (value !== null) {
      to.setItem(key, value);
      from.removeItem(key);
    }
  });
};

export const getAuthStorageStrategy = (): AuthStorageStrategy => {
  if (!isBrowser()) return DEFAULT_AUTH_STORAGE_STRATEGY;

  const saved = window.localStorage.getItem(AUTH_STORAGE_STRATEGY_KEY);
  if (saved === 'local' || saved === 'session') return saved;

  return DEFAULT_AUTH_STORAGE_STRATEGY;
};

export const setAuthStorageStrategy = (strategy: AuthStorageStrategy) => {
  if (!isBrowser()) return;

  window.localStorage.setItem(AUTH_STORAGE_STRATEGY_KEY, strategy);

  const local = window.localStorage;
  const session = window.sessionStorage;
  if (strategy === 'session') {
    migrateAuthTokens(local, session);
    return;
  }

  migrateAuthTokens(session, local);
};

export const createAuthStorage = (): SupportedStorage => ({
  getItem: (key: string) => {
    const storage = getStorageByStrategy(getAuthStorageStrategy());
    return storage?.getItem(key) ?? null;
  },
  setItem: (key: string, value: string) => {
    const storage = getStorageByStrategy(getAuthStorageStrategy());
    storage?.setItem(key, value);
  },
  removeItem: (key: string) => {
    const storage = getStorageByStrategy(getAuthStorageStrategy());
    storage?.removeItem(key);
  },
});

export const createSupabaseClient = () => createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: createAuthStorage(),
    persistSession: true,
    autoRefreshToken: true,
  },
});

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = createSupabaseClient();
